"""Python wrapper for the R package huge."""

import importlib.util as _importlib_util
from typing import Any

from . import core as _core
from .core import (
    HugeGeneratorResult,
    HugeInferenceResult,
    HugeResult,
    HugeRocResult,
    HugeSelectResult,
    HugeSelectSummary,
    HugeStockDataResult,
    HugeSummary,
    PyHugeError,
    huge,
    huge_ct,
    huge_glasso,
    huge_generator,
    huge_inference,
    huge_mb,
    huge_npn,
    huge_plot,
    huge_plot_graph_matrix,
    huge_plot_network,
    huge_plot_roc,
    huge_plot_sparsity,
    huge_roc,
    huge_select_summary,
    huge_select,
    huge_stockdata,
    huge_summary,
    huge_tiger,
)

__all__ = [
    "PyHugeError",
    "HugeResult",
    "HugeSelectResult",
    "HugeGeneratorResult",
    "HugeInferenceResult",
    "HugeRocResult",
    "HugeStockDataResult",
    "HugeSummary",
    "HugeSelectSummary",
    "huge",
    "huge_mb",
    "huge_glasso",
    "huge_ct",
    "huge_tiger",
    "huge_generator",
    "huge_inference",
    "huge_select",
    "huge_npn",
    "huge_roc",
    "huge_stockdata",
    "huge_summary",
    "huge_select_summary",
    "huge_plot",
    "huge_plot_sparsity",
    "huge_plot_roc",
    "huge_plot_graph_matrix",
    "huge_plot_network",
    "test",
    "doctor",
    "format_doctor_report",
]

__version__ = "0.2.2"


def doctor(require_runtime: bool = False) -> dict:
    """Run runtime diagnostics and return a structured report."""

    from .doctor import doctor as _doctor

    return _doctor(require_runtime=require_runtime)


def format_doctor_report(report: dict[str, Any]) -> str:
    """Render a human-readable report generated by ``doctor()``."""

    from .doctor import format_doctor_report as _format_doctor_report

    return _format_doctor_report(report)


def test(require_runtime: bool = False) -> dict:
    """Probe runtime readiness for pyhuge.

    Returns a status dict with keys:
    - ``python_import``: module import status
    - ``rpy2``: whether ``rpy2`` is discoverable
    - ``runtime``: whether R bridge and R package ``huge`` are usable

    If ``require_runtime=True``, raises ``PyHugeError`` when runtime is not ready.
    """

    status = {
        "python_import": True,
        "rpy2": _importlib_util.find_spec("rpy2") is not None,
        "runtime": False,
    }

    if not status["rpy2"]:
        if require_runtime:
            raise PyHugeError(
                "rpy2 is required for pyhuge runtime. Install with `pip install \"pyhuge[runtime]\"`."
            )
        return status

    try:
        _core._r_env()
        status["runtime"] = True
    except Exception as exc:  # pragma: no cover - runtime depends on local env
        if require_runtime:
            raise PyHugeError(
                "R runtime for pyhuge is unavailable. "
                "Check R installation, architecture match, and R package `huge` visibility."
            ) from exc

    return status
